### ISSUE TITLE
WBSTATS - Can't get Oil Data?

### ISSUE THREAD

**Issue by rulla** [GIST-ORNL/wbstats#10]
Hi All,
I ran the devtools::install_github("GIST-ORNL/wbstats")
but still cant get CRUDE_BRENT data? could you please help?
"oil_data <- wb(indicator = "CRUDE_BRENT", mrv = 10, freq = "M", POSIXct = TRUE)"
"No data was returned for any requested country and indicator. Returning empty data frame"

Thank you

**Comment by jpiburn** [comment]
thanks for letting me know. I'll look into this as soon as I can and come back with an update

**Comment by vincentarelbundock** [comment]
Hey there. I've been getting emails and improvement suggestions for my `WDI` packages. I hadn't looked at `wbstats` in a while, and wondered what it looked like these days. Very nice! Seems pretty much feature complete.

Honestly, I don't see much of a point in keeping up maintenance on `WDI` if you plan to keep `wbstats` rolling. But before I launch into deprecation cycle, I just want to make sure that you guys plan to keep it going. I hit this issue in my own tests, and it looks pretty old, so I'm just curious about your long term plans for the package.

Cheers!

**Comment by vincentarelbundock** [comment]
Sounds great. So here's the plan I'm leaning towards right now:

1. I'll test drive `wbstats` for a few weeks.
2. Wait for the final tiny little things to be implemented (issues already opened for the only things that still bring value to `WDI`).

Once all of this is done, I'll add a new argument to the main `WDI` function called `deprecation_warning`, which defaults to `TRUE`. When it remains on default `FALSE`, `WDI` will print a message saying that `wbstats` is more feature complete and that users are encouraged to move.

From there, I'll just leave `WDI` on CRAN to make sure that people's existing code doesn't break, but I won't be adding new features or doing much of anything unless something breaks and the fix is easy to implement.

I'm still thinking about this, but that seems like the most sensible plan at this juncture.
